# Use an official MySQL runtime as a parent image
FROM mysql:latest

# Define MySQL environment variables
ENV MYSQL_DATABASE=findfilmsdb
ENV MYSQL_USER=kurtis
ENV MYSQL_PASSWORD=carsch

# Install python and python-pip
RUN apt-get update && apt-get install -y \
    python \
    python-pip

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 3001 available to the world outside this container
EXPOSE 3001

# Define environment variable SERVER_SETTINGS to be in production mode
ENV SERVER_SETTINGS ./configs/production.cfg

# Run launch.py when the container launches
CMD ["python", "launch.py"]
