ifeq ($(PROJECT_DIR),)
    $(error PROJECT_DIR is not set)
endif

ifeq ($(GTEST_DIR),)
    $(error GTEST_DIR is not set)
endif

INCLUDE_PATH := \
	$(INCLUDE_PATH) \
    $(PROJECT_DIR)/Src \

RAW_INCLUDE_PATH := \
    $(RAW_INCLUDE_PATH) \
    -isystem $(GTEST_DIR)/include \

LIBRARY_PATH := \
    $(LIBRARY_PATH) \
    $(GTEST_DIR)/lib

TARGET_LIBS := \
    $(TARGET_LIBS) \
    gtest \
    gtest_main \

