TARGET_TYPE = program
TARGET_NAME = test_runner

include ../Array/makefile.exp
include ../BalancedTree/makefile.exp
include ../LinearStorageInterface/makefile.exp
include ../LinkedList/makefile.exp
include ../PigLatin/makefile.exp
include ../Queue/makefile.exp
include ../Shared_Ptr/makefile.exp
include ../Stack/makefile.exp
include ../Tree/makefile.exp
include ../Vector/makefile.exp

include ../test_engine/makefile.exp
include ../build.inc
